### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by lvchuandong** [yanzq95/DHD#2]
Excellent work. I want to know if there is a result with an input size 256x704, backbone resnet50, and history frames 8

**Comment by yanzq95** [comment]
Hi Chuandong,

Thank you for your interest in our work. Unfortunately, we only have 3090/4090 GPUs with 24GB memory, which do not support training with 8 history frames. However, you might be able to try it if possible.

**Comment by lvchuandong** [comment]
> Hi Chuandong,
> 
> Thank you for your interest in our work. Unfortunately, we only have 3090/4090 GPUs with 24GB memory, which do not support training with 8 history frames. However, you might be able to try it if possible.

Thank you very much.
