### ISSUE TITLE
COTR model results in the paper

### ISSUE THREAD

**Issue by lvchuandong** [yanzq95/DHD#3]
I saw in the paper that you have the result that the COTR model uses the history frame as 1. 
![image](https://github.com/user-attachments/assets/537b0b6b-45bb-4b46-b167-cd77b020e756)
If you trained the COTR model yourself, could you please provide the model weights for COTR? I would appreciate it

**Comment by yanzq95** [comment]
Hi Chuandong,
the mIoU (41.39) is referenced from Table 2 of the COTR paper. The results for its 17 classes were provided by Qihang Ma, the first author of COTR. You might consider reaching out to him for the checkpoint, as he is known to be kind and helpful !

**Comment by lvchuandong** [comment]
> Hi Chuandong, the mIoU (41.39) is referenced from Table 2 of the COTR paper. The results for its 17 classes were provided by Qihang Ma, the first author of COTR. You might consider reaching out to him for the checkpoint, as he is known to be kind and helpful !

Thank you very much!

**Comment by lvchuandong** [comment]
> Hi Chuandong, the mIoU (41.39) is referenced from Table 2 of the COTR paper. The results for its 17 classes were provided by Qihang Ma, the first author of COTR. You might consider reaching out to him for the checkpoint, as he is known to be kind and helpful !

![image](https://github.com/user-attachments/assets/65e7d37c-c6e9-4dbd-b85b-c4d41e8b7603)
Another question, you wrote in your paper that the backbone of COTR is SwinB and the mIoU is 46.20 when the history frame is 8 frames. Should the history frame be 1 frame?

**Comment by yanzq95** [comment]
According to the official settings of COTR, the history frame is 8 ~
If you have any other questions about the details, you can also discuss with us through the WeChat that is provided at my homepage, thks~

**Comment by lvchuandong** [comment]
> According to the official settings of COTR, the history frame is 8 ~ If you have any other questions about the details, you can also discuss with us through the WeChat that is provided at my homepage, thks~

Thank you very much!
