### ISSUE TITLE
数据集高度箱型图代码

### ISSUE THREAD

**Issue by zswzswzsw233** [yanzq95/DHD#4]
您好，绘制OccNuscenes数据集的高度分布箱型图代码能否分享一下？谢谢！

**Comment by Rayn-Wu** [comment]
你好，可以使用下面的代码绘制：
```
import matplotlib.pyplot as plt
data = {
    'driv. surf.': [23447247, 60022276, 124979644, 21951038, 6062441, 2465340, 1161664, 614157, 359833, 205275, 116620, 71868, 47524, 27841, 20479, 2071],
    'side walk': [6579920, 13326890, 28985775, 14582767, 3579165, 1266121, 589879, 283887, 136135, 71258, 42538, 27118,17907, 11507, 9695, 1037],
    'othrer flat': [409167, 852242, 3295835, 1270817, 338832, 107968, 47941, 14243, 5561, 3644, 2304, 1656, 1409, 1183, 719, 225],
    'terrian': [7524832, 11212004, 23566423, 16900359, 7791283, 4591685, 3060464, 2131687, 1557230, 1143683, 862916, 663012, 516359, 451629, 454117, 10816],
    'barrier': [25483, 150795, 746771, 1089558, 986245, 469473, 129912, 36652, 14592, 4650, 2155, 977, 232, 61, 49, 31],
    'traffic cone': [7079, 31299, 155325, 185081, 151895, 91052, 24022, 3316, 967, 423, 233, 141, 80, 64, 33, 20],
    'others': [38570, 145346, 427385, 592837, 530752, 382201, 211548, 128330, 89418, 59777, 42213, 26511, 17263, 10617, 6565, 5240],
    'bicycle': [2766, 13375, 46306, 71458, 67812, 47852, 23488, 8967, 2621, 922, 396, 149, 28, 7, 15, 41],
    'motocycle': [4305, 17057, 74683, 92497, 90587, 74576, 38873, 13242, 5525, 2479, 885, 297, 91, 31, 18, 11],
    'car': [378291, 1674185, 6684463, 7823688, 8382726, 7917022, 4869894, 1840376, 567730, 226492, 92839, 40601, 21404, 11089, 4395, 1532],
    'pedestrian': [35997, 132309, 456416, 692935, 768766, 757245, 590238, 316069, 109219, 44794, 20871, 9459, 3265, 1314, 689, 514],
    'truck': [78566, 397571, 1678257, 2080009, 2152939, 2169183, 1997272, 1692687, 1342885, 1124701, 825845, 536054,249734, 75648, 21993, 6482],
    'cons. veh.': [19151, 70193, 238040, 285195, 292714, 296638, 286449, 273639, 224667, 183192, 122279, 72507, 33333,11589, 6521, 4620],
    'bus': [43600, 175981, 554890, 610464, 642902, 736261, 819515, 842998, 803833, 665974, 436955, 207060, 105362,55861, 24948, 14631],
    'trailer': [26335, 134281, 493942, 597483, 638397, 642437, 618956, 607924, 612062, 599799, 558168, 482627, 320970, 128209, 29217, 6758],
    'manmade': [3768931, 7169829, 13352789, 19902348, 23114688, 23578075, 22420167, 21464002, 20515136, 19955697, 19094946, 18168060, 17170405, 16508762, 15616533, 14532089],
    'vegetation': [2694474, 4703427, 8330381, 12962674, 15787293, 16476401, 17254258, 19337268, 22097382, 25145279, 27332080, 28821242, 28872002, 28017853, 26401972, 24351712],
}


expanded_data = []
labels = []
max_height = 16

for i, (class_name, counts) in enumerate(data.items()):
    class_data = []
    for height, count in enumerate(counts, start=1):
        class_data.extend([height] * count)
    expanded_data.append(class_data)
    labels.append(class_name)
plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman'],
    'font.size': 13  
})

plt.figure(figsize=(12, 5))
boxplot = plt.boxplot(expanded_data, patch_artist=True, medianprops=dict(color='black'))

rgb_colors = [
    (255/255, 0/255, 255/255),   # driv_surf
    (75 / 255, 0 / 255, 75 / 255),  # side_walk
    (139/255, 137/255, 137/255),   # othrer_flat
    (150/255, 240/255, 80/255),    # terrian
    (255 / 255, 120 / 255, 50 / 255),  # barrier
    (255 / 255, 240 / 255, 150 / 255),  # traffic_cone
    (0/255, 0/255, 0/255),   # others
    (255 / 255, 192 / 255, 203 / 255),  # bicycle
    (200 / 255, 200 / 255, 0 / 255),  # motocycle
    (0 / 255, 150 / 255, 245 / 255),  # car
    (255 / 255, 0 / 255, 0 / 255),  # pedestrian
    (160 / 255, 32 / 255, 240 / 255),  # truck
    (0 / 255, 255 / 255, 255 / 255),  # cons_veh.
    (255 / 255, 255 / 255, 0 / 255),  # bus
    (135 / 255, 60 / 255, 0 / 255),  # trailer
    (230/255, 230/255, 250/255),   # manmade
    (0/255, 175/255, 0/255),  # vegetation
]

for patch, color in zip(boxplot['boxes'], rgb_colors):
    patch.set_facecolor(color)
plt.xticks(ticks=range(1, len(labels) + 1), labels=labels, rotation=15, ha="right")

plt.gca().invert_yaxis()
plt.grid(True)
plt.savefig('box_plot.png', dpi=500)
plt.show()
```
其中，“data” 是我们遍历 gt 后统计的各个类别在1-16高度上的结果。

**Comment by zswzswzsw233** [comment]
辛苦了，非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月8日(周五) 下午3:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yanzq95/DHD] 数据集高度箱型图代码 (Issue #4)




 
你好，可以使用下面的代码绘制：
 import matplotlib.pyplot as plt data = {     'driv. surf.': [23447247, 60022276, 124979644, 21951038, 6062441, 2465340, 1161664, 614157, 359833, 205275, 116620, 71868, 47524, 27841, 20479, 2071],     'side walk': [6579920, 13326890, 28985775, 14582767, 3579165, 1266121, 589879, 283887, 136135, 71258, 42538, 27118,17907, 11507, 9695, 1037],     'othrer flat': [409167, 852242, 3295835, 1270817, 338832, 107968, 47941, 14243, 5561, 3644, 2304, 1656, 1409, 1183, 719, 225],     'terrian': [7524832, 11212004, 23566423, 16900359, 7791283, 4591685, 3060464, 2131687, 1557230, 1143683, 862916, 663012, 516359, 451629, 454117, 10816],     'barrier': [25483, 150795, 746771, 1089558, 986245, 469473, 129912, 36652, 14592, 4650, 2155, 977, 232, 61, 49, 31],     'traffic cone': [7079, 31299, 155325, 185081, 151895, 91052, 24022, 3316, 967, 423, 233, 141, 80, 64, 33, 20],     'others': [38570, 145346, 427385, 592837, 530752, 382201, 211548, 128330, 89418, 59777, 42213, 26511, 17263, 10617, 6565, 5240],     'bicycle': [2766, 13375, 46306, 71458, 67812, 47852, 23488, 8967, 2621, 922, 396, 149, 28, 7, 15, 41],     'motocycle': [4305, 17057, 74683, 92497, 90587, 74576, 38873, 13242, 5525, 2479, 885, 297, 91, 31, 18, 11],     'car': [378291, 1674185, 6684463, 7823688, 8382726, 7917022, 4869894, 1840376, 567730, 226492, 92839, 40601, 21404, 11089, 4395, 1532],     'pedestrian': [35997, 132309, 456416, 692935, 768766, 757245, 590238, 316069, 109219, 44794, 20871, 9459, 3265, 1314, 689, 514],     'truck': [78566, 397571, 1678257, 2080009, 2152939, 2169183, 1997272, 1692687, 1342885, 1124701, 825845, 536054,249734, 75648, 21993, 6482],     'cons. veh.': [19151, 70193, 238040, 285195, 292714, 296638, 286449, 273639, 224667, 183192, 122279, 72507, 33333,11589, 6521, 4620],     'bus': [43600, 175981, 554890, 610464, 642902, 736261, 819515, 842998, 803833, 665974, 436955, 207060, 105362,55861, 24948, 14631],     'trailer': [26335, 134281, 493942, 597483, 638397, 642437, 618956, 607924, 612062, 599799, 558168, 482627, 320970, 128209, 29217, 6758],     'manmade': [3768931, 7169829, 13352789, 19902348, 23114688, 23578075, 22420167, 21464002, 20515136, 19955697, 19094946, 18168060, 17170405, 16508762, 15616533, 14532089],     'vegetation': [2694474, 4703427, 8330381, 12962674, 15787293, 16476401, 17254258, 19337268, 22097382, 25145279, 27332080, 28821242, 28872002, 28017853, 26401972, 24351712], } expanded_data = [] labels = [] max_height = 16 for i, (class_name, counts) in enumerate(data.items()):     class_data = []     for height, count in enumerate(counts, start=1):         class_data.extend([height] * count)     expanded_data.append(class_data)     labels.append(class_name) plt.rcParams.update({     'font.family': 'serif',     'font.serif': ['Times New Roman'],     'font.size': 13   }) plt.figure(figsize=(12, 5)) boxplot = plt.boxplot(expanded_data, patch_artist=True, medianprops=dict(color='black')) rgb_colors = [     (255/255, 0/255, 255/255),   # driv_surf     (75 / 255, 0 / 255, 75 / 255),  # side_walk     (139/255, 137/255, 137/255),   # othrer_flat     (150/255, 240/255, 80/255),    # terrian     (255 / 255, 120 / 255, 50 / 255),  # barrier     (255 / 255, 240 / 255, 150 / 255),  # traffic_cone     (0/255, 0/255, 0/255),   # others     (255 / 255, 192 / 255, 203 / 255),  # bicycle     (200 / 255, 200 / 255, 0 / 255),  # motocycle     (0 / 255, 150 / 255, 245 / 255),  # car     (255 / 255, 0 / 255, 0 / 255),  # pedestrian     (160 / 255, 32 / 255, 240 / 255),  # truck     (0 / 255, 255 / 255, 255 / 255),  # cons_veh.     (255 / 255, 255 / 255, 0 / 255),  # bus     (135 / 255, 60 / 255, 0 / 255),  # trailer     (230/255, 230/255, 250/255),   # manmade     (0/255, 175/255, 0/255),  # vegetation ] for patch, color in zip(boxplot['boxes'], rgb_colors):     patch.set_facecolor(color) plt.xticks(ticks=range(1, len(labels) + 1), labels=labels, rotation=15, ha="right") plt.gca().invert_yaxis() plt.grid(True) plt.savefig('box_plot.png', dpi=500) plt.show()  
其中，“data” 是我们遍历 gt 后统计的各个类别在1-16高度上的结果。
